INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و همراهی ترس", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و یکسانی ترس", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و حسن ظن به خدا", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و خواستن", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و دعاها", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و همراهی تلاشگری", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید کمک کننده عمل", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و رحمت الهی", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و نعمت ها", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید در امور دنیوی و اخروی", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و پرهیز از غفلت", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و پرهیز از عصیانگری", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید و پرهیز از مکر الهی", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید غیرعاقلانه", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید در سختیها", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امید دروغین", 1);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اشتیاق به شهادت", 2);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اعتماد به خدا", 2);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ترجیح دادن محبت خدا، پیامبر اسلام و جهاد", 2);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اشتیاق به زندگی", 2);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("درخواست شهادت از خداوند", 2);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آرزوی مرگ", 2);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رعایت اخلاق", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حقوق", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تغذیه", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رابطه زناشویی", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رسیدگی به ظاهر", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کمک کاری", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آموزش و اجرای دین", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تشویق و تنبیه", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهتمام به همسر", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نفقه", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کرامت همسر", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اعتماد", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت درست", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تعدد زوجات", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("غیرت و حساسیت", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("استفاده از امکانات خانه", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افتخار یا سرافکندگی", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیزی از مواضع تهمت", 3);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("برنامه ریزی", 5);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("چالش ها و پیشروی ها", 5);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ارتباطات", 5);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تفکر", 5);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حریص بودن", 7);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شتاب زدگی", 7);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بخیل بودن", 7);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهل جزع و فزع بودن در برخورد با مشکلات", 7);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("طغیان و غرور بر اثر برخورداری", 7);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شک در معاد", 7);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شدت در ناامیدی", 7);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ناسپاس بودن", 7);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حمایت مالی", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ظلم", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مواسات", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ابراز علاقه", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مهربانی", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("روابط هم‌افزا", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم بی‌تفاوتی", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم خیانت", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("یاری کردن", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("غمخوار بودن", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم سرزنش", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم عیبجویی", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم غیبت", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم محروم سازی", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دیدار در هنگام سلامت و مریضی", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دعا کردن هنگام عطسه", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پذیرش دعوت دوستان", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شرکت در تشییع جنازه", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیز از فریب و خدعه", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش استحکام پیمان ها", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("انسجام در برابر دشمن", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پناه دادن به مظلومین نزدیک", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دادرسی نسبت به مظلومین دور", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تقسیم مساوی غنایم", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم خیانت قلبی در سه محور اخلاص عملی، اطاعت از پیشوای حق و التزام به جامعه حق", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیز از هر نوع زیان زدن", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش خیر و کاهش شر", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("قهر نکردن", 8);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ویژگی های شخصی و جسمی", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("فقط ترس از خداوند", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ترجیح دادن رضایت خدا بر رضایت مردم", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("انجام عمل در بلند مدت", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش شجاعت بر اساس اعتقاد به خدا", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مقابله با ستمکاران", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ترس از دیگران", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم قهقه زدن", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم سرمستی", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کنترل احساسات و حالات", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عمل بر اساس دانش و آینده نگری", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش توجه به تاثیر اعمال", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیز از شهوت و دوری از وابستگی به دنیا", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش اخلاص", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش قدرت بدنی و روحی", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ترجیح امور اخروی بر امور دنیوی در انتخاب‌ها ", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش سطح کیفی عبادات", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کوتاهی آرزو و عدم تلاطم", 11);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("انکسار همیشگی و فراگیر", 19);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رشد در همه شرایط", 19);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تداوم در عمل خیر", 19);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تسلیم", 19);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("وجل", 19);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صبر", 19);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیز از غرور و آروزی بلند", 19);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تقویت تقوا", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("استفاده بهینه از نعمات الهی و طلب آمرزش", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("انفاق و پرهیز از نابودگری", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت خشم و گذاشت از دیگران", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رعایت رفتارهای شناخته شده به نیکی", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("جهاد در هر شرایطی", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صبر کردن", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صدق در گفتار و اعمال", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عمومیت احسان", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سرعت بالای انس", 18);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پیروزی ها و شکست ها", 17);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عمل به برنامه خدا", 17);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("غفلت", 17);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نجات", 17);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بن بست", 17);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کنترل شخصیت", 17);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("زینت", 17);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نیت گناه و ترک طاعت", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ارتکاب و آلودگی به گناه و ترک طاعت", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوشحالی حین گناه و ترک طاعت", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عقب انداختن توبه و سطحی بودن پشیمانی بعد از گناه و ترک طاعت", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کوچک شمردن گناه و ترک طاعت", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تکرار گناه و ترک طاعت", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوشحالی بعد از  گناه و ترک طاعت", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اظهار گناه و ترک طاعت", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رضایت به  گناه و ترک طاعت دیگران ", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کمک به دیگران درارتکاب گناه و ترک طاعت آنها", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("گمراه کردن دیگران به سمت گناه و ترک طاعت ", 21);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نیت طاعت و ترک گناه", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("انجام طاعت و ترک گناه", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بالا بردن اخلاص عمل", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES (" خوشحالی از انجام طاعت و ترک گناه", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("استقامت در انجام طاعت و ترک گناه", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کوچک شمردن انجام طاعت و بزرگ دیدن معصیت", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تکرار و تداوم در انجام طاعت و ترک معصیت", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اخفاء طاعت ", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رضایت به طاعات دیگران و تنفر از گناهان آنها  ", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کمک به دیگران در امتثال طاعات و تنفر از گناهان آنها", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("هدایت دیگران در امتثال طاعات و تنفر از گناهان آنها  ", 20);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تناسخ", 16);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("به کار گیری تشبیه به خلق برای خداوند", 16);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اجبار و واگذاری", 16);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شک در خدا و پیامبر", 16);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بغض و تنفر نسبت به اهل بیت", 16);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ادعای دروغین امامت", 16);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نفی منجی", 16);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("احساس حقارت در برابر فرهنگ بیگانه", 16);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تزلزل یقین", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم آینده نگری", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بیماری درونی", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم عقلانیت در انتخاب ها", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("فریب عافیت ها و برخورداری ها", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سطح دانش پایین", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش سردرگمی و حیرت", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم تفکر زیاد", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم اخلاص و یقین زیاد", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کفران", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش عصبان", 12);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مصونیت از اشتباه", 13);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دوستی و دشمنی بر اساس نظر شخصی", 13);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اطاعت غافلانه از شیطان", 13);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("هنراهی علما در حرام", 13);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اطاعت در معصیت", 13);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ریا و سمعه", 13);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اشتباه در تشخیص عامل", 13);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رشوه", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کبر", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اطاعت بر اساس گمان", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پذیرش ولایت طاغوت", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم پذیرش خدا، فرشتگان، کتاب های آسمانی و فرستادگان خدا", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("گسترش انکار در زندگی", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("انکار و ترک واجبات", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ستمکار", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهل لذت های زودگذر بودن", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوشایندی نسبت به دنیا", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("فریب کاری، سنگدلی و خیانتکاری", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پستی و غرور", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دنیا و شهوت", 14);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم تجمیع فهم دین و خوش اخلاقی", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("غیبت، حسادت و عدم کمک", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم پذیرش امر به معروف و نهی از منکر و خواب و خوراک زیاد", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نماز بد", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بدون منفعت بودن", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دروغگو بودن", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خلف وعده و خیانت", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سهل گیری بر خود و سخت گیری بر مردم", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("گفتار زیبا و عمل زشت", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("گفتار زیبا و عمل مضر", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بی حیا و کودن بودن", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مضر و بدگمان بودن", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سکوت و غفلت ", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("قساوت قلب و تکرار گناه", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تفاوت پنهان و آشکار", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بیشتر بودن خشوع بدن از خشوع قلب", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تلون اخلاق", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("موافقت زیاد", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آخرت وسیله برای رسیدن به دنیا", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دشمنی با خوبان", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بدگویی و عیب جویی", 15);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("طاعات", 10);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("محرمات", 10);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عافیت ها و برخورداری ها", 10);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مشکلات و مصائب", 10);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت مالی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عقلانیت", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عمومیت مدارا", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوش اخلاقی با مردم", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ترک حق", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("گذشت", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("افزایش سطح صمیمیت", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بهره مندی از همراهی مردم", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دست یابی به اهداف", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوش کلامی و گشاده رویی", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بهینه سازی زندگی ", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کاهش و از بین بردن ضرر", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ارتقای امنیت خود و اطرافیان", 23);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شخصی باطنی ", 24);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شخصی ظاهری", 24);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اجتماعی داخلی", 24);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اجتماعی خارجی", 24);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حقوق", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تنبلی و تلاش", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صمیمیت", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اطاعت", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("توقعات", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("محبت", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مهریه", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خدمت", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اموال شوهر", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کمک در تامین نفقه", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بهترین بودن", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تولید و مصرف", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("فرزند", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تمکین", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رضایت", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کنترل خشم", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سازگاری", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اخلاق", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دینداری", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مشارکت های اجتماعی", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تعدد زوجات", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("زیبایی و دلبری", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم حضور شوهر", 4);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تغذیه", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آرامش و امنیت عاطفی", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رشد شخصیت مستقل کودک", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("میزان محبت و برقراری ارتباط با والدین", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مهارت کارگروهی", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تفکر", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مسئولیت پذیری", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صبوری", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تلاشگری", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("با نشاط", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ازدیاد تربیت و ادب متناسب با افزایش دانش", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کمک در منزل", 25);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کیفیت و کمیت نماز", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیز از انجام کارهای بیهوده و اهتمام به امور اخروی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرداخت زکات", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت آلات جنسی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امانتداری", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("روابط هم افزا با خوبان", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دیدگاه نسبت به دنیا و امور دنیوی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اقرار در گفته ها، عمل در رفتار و معرفت عاقلانه", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت زبان", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عمل برای خدا(نیت)", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پناه بردن به خداوند در بر ابر تعریف دیگران و طلب آمرزش برای عیب‌های پنهان ", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("معامله دارایی خود با خدا به جهت مبارزه برای تحقق حاکمیت خدا", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رسیدگی به یتیمان", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مقید به نظافت شخصی و آراستگی ظاهر", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("وفای عهد", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شب زنده داری", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دلیری در روز", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("روزه داری", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("همسایه داری", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آرامش هنگام راه رفتن", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شرکت در تشییع جنازه", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("وقار و نرم خوبی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حلم و صبوری", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ظلم و بخشش ظلم دیگران", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم بخل و صبر بر بخل دیگران", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوش اخلاق", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("استحکام در دین و عقیده", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدارا کردن با مردم", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دور اندیشی همراه با نرمی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آرامش و سکینه", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تلاشگری و مجاهدت", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نیکوکاری در استقامت", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شکر گزاری", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سلامت باطنی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت دانش", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ورع و پرهیزکاری", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("داشتن تقوا", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اطعام فقیران", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بی اهمیتی به دااریی دیگران", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیز از قطع رحم", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت نگاه", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت شکم", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم حسادت", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("یاری مظلومان", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سخت گیری بر خویش و آسایش مردم از او", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم هول و ترس از حل مشکلات مردم", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("محبت و تنفر", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مشورت به دیگران", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("یاری دهنده", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دوری از باطل، سخنان ناسزا و نادانی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دنبال شهرت نبودن", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهل مسافرت و مهاجرت", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("گریه برای خدا", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت قدرت", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیز از دوستی و دوری کردن از افراد سقوط کرده", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوابیدن بدون تجملات", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پرهیز از بستن معابر", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("رعایت حدود الهی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بدترین فرد نزد مردم بد و بهترین فرد نزد خداوند", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ترس از خدا", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مراقبت از دیگران (انجام امر به معروف و نهی از منکر)", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهل عبادت بودن", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اطاعت‌پذیری از شایستگان", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("زیرکی بسیار", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("علاقه ی خوبان به همنشینی با آن‌ها", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بجاآوردن حج", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("داشتن تواضع و فروتنی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهل توبه و استغفار بودن", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("احسان به والدین", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مهلت دادن به مقروضین", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهل تلاوت قرآن", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پناه دادن و یاری کردن مهاجران", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("احترام به عقاید دیگران", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("استفاده از تجارب و پرهیز از تجربه شکست مکرر", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("داشتن انصاف", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت خوب زندگی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ابراز احساسات نسبت به طاعت و معصیت", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پربازده کم مصرف", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مدیریت رضایت و نارضایتی", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بدون ترس و غم", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("یقین داشتن", 9);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مقدم کردن اسلام و اهل بیت", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اضطرار به حاکمیت حجت خدا", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صبوری", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دعا کردن", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عمل به دستورات دین", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("انسجام و هم افزایی اجتماعی", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شناخت و رصد میزان تحقق نشانه های ظهور حضرت", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("انجام اعمال نیک به نیابت یا برای حضرت ", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ایمان به حضرت", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مبارزه", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("هوشیاری", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("علوم اهل بیت", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تجدید بیعت", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حفظ و ارتقای آمادگی", 26);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوش بویی امام", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مهر امامت میان کتف ها", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ختنه کرده به دنیا آمده", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تولد پاک", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بینایی از پشت سر همانند بینایی از جلو", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم سایه", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم احتلام", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خواب چشمان نه دل", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تناسب زره پیامبر فقط برای او ", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ندیدن ادرار و مدفوع او", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("با وقار", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آرامش", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امانت دار", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("فصیح ترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("زاهد", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بخشنده", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهل قناعت", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("متواضع¬ترین مردم در برابر خداوند", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اهل عبادت", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مهربانترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("با غیرت", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صبور", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("موافق", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("مرافق", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("گشاده دست ترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خوش قول ترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حسن خلق", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عالمترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حاکمترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("با تقواترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حلیم ترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ورع", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شجاعترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بنده ترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("حکیم ترین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("هدایت گری و راهنمائى", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اقرار به برترى او در خاندان رسول خدا", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("برپا داشتن نماز", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دادن زکات", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امر به معروف", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نهی از منکر", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدل", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("احسان", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ریشه دار بودن", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عرب بودن", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سیادت", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("فرزند امام حسین", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("از قبیله معروف", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نسب معروف", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خانواده معروف", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بزرگترين فرزند پدرش", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خروج یمانی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خروج سفیانی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خروج خراسانی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("ندای آسمانی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("فرو رفتن زمين در بيداء", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("كشتن نفس زكيّه", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اقتدای حضرت عیسی به حضرت مهدى در نماز", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("زنده کردن مردگان", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("شفا دادن پیسی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("بینا کردن کور", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("جوان کردن پیر", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صحبت کردن با زبان مخاطب", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("صحبت کردن با لهجه مخاطب", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("گفتن شهادتین هنگام تولد با صداى بلند", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("محدث بودن", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("استجابت دعا", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("همه علوم انبیا گذشته", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("همه دانش های بین مردم", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نمی گوید نمی دانم", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دانستن احکام الهی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("پاسخگوی همه پرسش های مخاطبان", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آگاهی از امور فراموش شده", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("زبان حیوانات", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خبر ازآینده", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("خبر از دل مردم", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("آگاهی از زندگی افراد", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نقش کردن بر روی سنگ", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ظلم", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ارتکاب حرام", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ارتباط با منجمان", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ارتباط با پیشگویان", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ارتباط با فالگیر", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("همیشه در حال اجرای دستورات الهی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ارتکاب حرام های زبان", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ارتکاب حرام های شكم", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم ارتکاب حرام های جنسی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دوری از فرهنگ جاهلي", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("سزاوارتر از مردم به مردم", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم اشتباه در فتوى", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم سهو و نسيان", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم لهو و بازى در امور دنيا", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم حرص", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم حسد", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("عدم غضب", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("اسلحه جنگى پیامبر اسلام", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("كتابى كه در آن نام¬ شيعيان و دشمنان او تا روز قيامت در آن ثبت شده ", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کتاب جامعه که همه نیازمندی های مردم در آن ثبت شده", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("کتاب های انبیاء قبلی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("جفر اكبر و اصغر", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("وصيت آشكار", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("امام علی يعنى ذو الفقار", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("وصیت امام قبل", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نزديكترين شخص به امام قبل", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تصریح به امامت او", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("دوازدهمین نفر از  امامان", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نصب توسط امام قبلی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("نص", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("تایید به روح الهی", 27);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("روحیه سودگرا", 6);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("روحیه ترس محور", 6);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("روحیه محبت و متنفر", 6);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("روحیه خردورز", 6);
INSERT INTO `indicators` (`title`, `test_id`) VALUES ("روحیه قدرشناس", 6);
